### ISSUE TITLE
How can I use it inside a React project?

### ISSUE THREAD

**Issue by arnaugomez** [soulwire/sketch.js#106]
I have tried many ways (looking for an npm package, importing the file, etc.) but none has worked yet.

**Comment by arnaugomez** [comment]
I also think it would be extremely useful to convert particles.js into an npm package, but, as a front-end developer, I lack the technical expertise. If somebody would like to teach me or show me a way I can learn to do it...

**Comment by ayushgupta0110** [comment]
I also tried and search various things on how to use sketch.js with react but nothing worked. 
Could someone please help?
I need to make a component in React
