### ISSUE TITLE
Doesnt work within an Android WebView

### ISSUE THREAD

**Issue by caltv** [soulwire/sketch.js#66]
When I use this within a native Android WeWiew (4.4+) no lines are drawn...The page loads successfully and no errors are thrown, however it works fine in an the Chrome browser on the same device...

**Comment by caltv** [comment]
The answer,  hardware accelerated canvas rendering is not supported in Chromium WebView

Fix is   webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);

**Comment by soulwire** [comment]
Thanks for the report. As far as you know can anything be done in the sketch code to mitigate this? If not I'll close the issue though your solve in the comment above will help anyone who has come across this.

**Comment by caltv** [comment]
I don't think the JS Canvas API gives an option to enable//disable  hardware acceleration, so you can close...
