### ISSUE TITLE
[enhancement] Package as an NPM module

### ISSUE THREAD

**Issue by JasonStorey** [soulwire/sketch.js#69]
Would be nice if Sketch was on NPM. Just needs a package.json.

There's already a 'sketch' on NPM... I guess package name could be 'sketch-js'.

I can send a PR if you like?

**Comment by JasonStorey** [comment]
https://github.com/soulwire/sketch.js/pull/70

**Comment by soulwire** [comment]
Thanks for adding that @JasonStorey
