### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by upq** [soulwire/sketch.js#81]
Any usage with angular example?

**Comment by ktajpuri** [comment]
### Can you please explain a bit ?
There are lot of examples available online with angular
[Angular Example](https://hello-angularjs.appspot.com/helloworld)
The above is a good example.

**Comment by upq** [comment]
Really?
I used the very basic example from codepen in my angular app, 2 issues were there,
1. You have to destroy the instance your self because it doesnt get destroyed with state change (ui-router) and causes huge memory leak.
2. Using the angular $window you get undefined for one of the arrays that gets created with Sketch.create (can't remember which one that was 10 days ago .....) anyway when I initiated an empty array with the same name everything goes fine, and using the normal window object doesn't work.

and thanks for the angular hello world example.

**Comment by ktajpuri** [comment]
# I am sorry buddy..
I thought you were looking for a basic angular example .

**Comment by upq** [comment]
You thought I was looking for angular hello world example in the Sketch.js repo.....??
If so I'm really speechless... and wish you a good luck... some really good luck!.
